### ISSUE TITLE
KeyError when running qbic.py 

### ISSUE THREAD

**Issue by yangyxt** [vincentiusmartin/QBiC-Pred#11]
I run the qbic.py to generate TF binding predictions locally. Here is the code:
`# Run the qbic command 
python3 ${central_scripts}/QBiC-Pred/qbic-offline/qbic.py \
-i ${table::-4}.qbicinput.vcf \
-g ${qbic_tflist} \
-c hg19 \
-o ${table::-4}.tfpredictons.tsv`

I input the VCF format, and it looks like this:
![image](https://user-images.githubusercontent.com/40780228/88504485-7edd4400-d007-11ea-9254-62573ab07b1d.png)
As to the -g argument, the TF list is input as a one-column file and it looks like this:
![image](https://user-images.githubusercontent.com/40780228/88504547-acc28880-d007-11ea-85fb-b441b50b9855.png)

Here is the Error Message I got when running this command:
![image](https://user-images.githubusercontent.com/40780228/88504374-2a39c900-d007-11ea-86ba-eb2fdce94427.png)

Pls help debug it. Thanks!

**Comment by vincentiusmartin** [comment]
The .vcf is in the wrong format. See here https://www.internationalgenome.org/wiki/Analysis/Variant%20Call%20Format/vcf-variant-call-format-version-40/
Also example http://qbic.genome.duke.edu/download/QBiC-vcf-example-MAFK-ASB-variants.vcf

qbic needs the first 5 columns of the .vcf file which is chrom,pos,id,ref,alt. You can just put a dot on id since it's not needed by qbic.

**Comment by yangyxt** [comment]
> The .vcf is in the wrong format. See here https://www.internationalgenome.org/wiki/Analysis/Variant%20Call%20Format/vcf-variant-call-format-version-40/
> Also example http://qbic.genome.duke.edu/download/QBiC-vcf-example-MAFK-ASB-variants.vcf
> 
> qbic needs the first 5 columns of the .vcf file which is chrom,pos,id,ref,alt. You can just put a dot on id since it's not needed by qbic.

Thanks for the info. I just found the reason by identifying a malformed line in my VCF file. Thanks again!
