### ISSUE TITLE
OSError in offline qbic.py 

### ISSUE THREAD

**Issue by yangyxt** [vincentiusmartin/QBiC-Pred#13]
I have ran into this error using the offline qbic.py
![image](https://user-images.githubusercontent.com/40780228/92263771-c234a780-ef0f-11ea-9769-78b53adad2d8.png)
And after googling, I found a relative discussion https://bugs.python.org/issue13978.

Pls show me how to solve this if you have any idea. I haven't used the manager class in multiprocess module. I'm not sure how to help debug this. Thanks!

**Comment by yangyxt** [comment]
Since the traceback log does not mention the precise line causing the issue. I believe this error occurs in the highlighted part below:
<img width="775" alt="image" src="https://user-images.githubusercontent.com/40780228/92264174-69b1da00-ef10-11ea-977f-23eaa1ac3d1a.png">

And you are returning a lazy iterable class to postprocess() function. And after pd.concat command, the lazy iterables are all executed to retrieve the results. At that time, I can't add a command to close the multiprocess manager as suggested by the discussion pasted above.

**Comment by vincentiusmartin** [comment]
it's hard to see just from the traceback since it doesn't show which line from qbic is responsible.
But there are a few things I have in mind:
1. In the latest version of qbic, we changed completely to concurrent.futures, which is a wrapper for the multiprocessing library. I just removed all calls to multiprocessing from the code, you can try running with my latest update.
2. What python version are you using? concurrent.futures is pretty new and it requires python3. So you might want to update your python version

**Comment by yangyxt** [comment]
Thanks for the reply! Just tried the latest update and haven't encounter the same issue by far!
